apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flask-app
  namespace: argocd
spec:
  project: default

  source:
    repoURL: git@github.com:jonasmarquez/keepcoding-masters-proyecto-final.git
    targetRevision: HEAD
    path: k8s
    directory:
      recurse: true 

  destination:
    server: https://kubernetes.default.svc

  syncPolicy:
    syncOptions:
    - CreateNamespace=false
    
    automated:
      selfHeal: true
      prune: true
