apiVersion: v1
kind: Secret
metadata:
  name: argoproj-ssh-creds
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repo-creds
stringData:
  type: git
  url: git@github.com:jonasmarquez/keepcoding-masters-proyecto-final.git
  sshPrivateKey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
    QyNTUxOQAAACBXD/tlnWNHdrsTppuo/+w1zmrWNFw4tQNCafU28G8QKAAAAJh+z//tfs//
    7QAAAAtzc2gtZWQyNTUxOQAAACBXD/tlnWNHdrsTppuo/+w1zmrWNFw4tQNCafU28G8QKA
    AAAEAAmUHqVSOuOB/WvLVeNEgvvAdmZjHGmQYy0l9l6XBe7FcP+2WdY0d2uxOmm6j/7DXO
    atY0XDi1A0Jp9TbwbxAoAAAAD2ZyYW5jZXNjQHVidW50dQECAwQFBg==
    -----END OPENSSH PRIVATE KEY-----