{
 "title": "Number of calls to endpoints",
 "time": { "from": "2022-04-07T16:48:57.502Z", "to": "2022-04-07T16:59:25.459Z" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_pod_info, namespace)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(kube_pod_status_phase{namespace=~\"$namespace\",phase=\"Running\"},pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Number of calls to server in last hour",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(server_requests_total{namespace=\"$namespace\"}) - sum(min_over_time(server_requests_total{namespace=\"$namespace\"} [1h]))"
    }
   ]
  },
  {
   "title": "Number of calls to get list endpoint in last hour",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(get_list_requests_total{namespace=\"$namespace\"}) - sum(min_over_time(get_list_requests_total{namespace=\"$namespace\"} [1h]))"
    }
   ]
  },
  {
   "title": "Number of calls to create endpoint in last hour",
   "type": "stat",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(create_requests_total{namespace=\"$namespace\"}) - sum(min_over_time(create_requests_total{namespace=\"$namespace\"} [1h]))"
    }
   ]
  },
  {
   "title": "Number of calls to get student endpoint in last hour",
   "type": "stat",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(get_student_requests_total{namespace=\"$namespace\"}) - sum(min_over_time(get_student_requests_total{namespace=\"$namespace\"} [1h]))"
    }
   ]
  },
  {
   "title": "Number of calls to delete student endpoint in last hour",
   "type": "stat",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(delete_student_requests_total{namespace=\"$namespace\"}) - sum(min_over_time(delete_student_requests_total{namespace=\"$namespace\"} [1h]))"
    }
   ]
  },
  {
   "title": "Number of calls to update student endpoint in last hour",
   "type": "stat",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(update_student_requests_total{namespace=\"$namespace\"}) - sum(min_over_time(update_student_requests_total{namespace=\"$namespace\"} [1h]))"
    }
   ]
  },
  {
   "title": "Number of calls to main endpoint in last hour",
   "type": "stat",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(main_requests_total{namespace=\"$namespace\"}) - sum(min_over_time(main_requests_total{namespace=\"$namespace\"} [1h]))"
    }
   ]
  },
  {
   "title": "Number of calls to healthcheck endpoint in the last hour",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "healthcheck_requests_total{namespace=\"$namespace\"} - min_over_time(healthcheck_requests_total{namespace=\"$namespace\"} [1h])"
    }
   ]
  },
  {
   "title": "Memory usage vs Memory requests namespace",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(container_memory_usage_bytes{namespace=\"$namespace\"}) by (pod)",
     "legendFormat": "{{ pod }} memory usage"
    },
    {
     "expr": "avg(kube_pod_container_resource_requests{resource=\"memory\",namespace=\"$namespace\"}) by (pod)",
     "legendFormat": "{{pod }} memory requests"
    }
   ]
  },
  {
   "title": "Memory usage vs Memory requests by pod",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\", pod=\"$pod\"}) ",
     "legendFormat": "{{ pod }} memory usage"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{namespace=\"$namespace\", resource=\"memory\", pod=\"$pod\"})",
     "legendFormat": "{{pod }} memory requests"
    }
   ]
  }
 ]
}