apiVersion: v1
kind: Service
metadata:
  name: flask-nodeport
  namespace: flask-api
  labels:
    app: flaskapp
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
    nodePort: 32001
  selector:
    app: flaskapp
  type: NodePort

