version: '3.9'

services:
  app:
    build: .
    container_name: flask_app
    restart: unless-stopped
    environment:
     MYSQL_HOST: ${MYSQL_HOST}
     MYSQL_USER: ${MYSQL_USER}
     MYSQL_PASSWORD: ${MYSQL_PASSWORD}
     MYSQL_DB: ${MYSQL_DB}
    ports:
     - 5000:5000
    depends_on:
      - db
    volumes:
      - ./app.py:/app/app.py
  db:
    container_name: db
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
     MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
     MYSQL_DATABASE: ${MYSQL_DATABASE}
     MYSQL_USER: ${MYSQL_USER}
     MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
     - 3306:3306
    expose:
     - 3306
    volumes:
     - my-db:/var/lib/mysql

volumes:
 my-db:
